### PR TITLE
Calculator setup

### PR DESCRIPTION
**Pull request by che30**
In this branch I carried out the following: 
- Added a props-type
- Added a big.js

### CODE REVIEW

**Review by mahmoud717 — CHANGES_REQUESTED** [review]
### Changes required ♻️ 

**Hello @che30**

Great job with the project so far it looks amazing, but there are still some changes to be made:
 
---
### Requested 🔴 

- [x] Please make sure to add a professional readme file to your project. 
- [x] Please make sure to add the big.js and prop-types packages to your app's dependencies.
- [x]  Please make sure to del=ploy your app to heroku or any deployment service.


---

please make these changes and request another code review.

if you have any questions don't hesitate to contact me on slack **MahmoudMohammad**

**Comment by che30** [comment]
> ### Changes required 
> **Hello @che30**
> 
> Great job with the project so far it looks amazing, but there are still some changes to be made:
> 
> ### Requested 
> * [x]  Please make sure to add a professional readme file to your project.
> * [x]  Please make sure to add the big.js and prop-types packages to your app's dependencies.
> * [x]   Please make sure to del=ploy your app to heroku or any deployment service.
> 
> please make these changes and request another code review.
> 
> if you have any questions don't hesitate to contact me on slack **MahmoudMohammad**

Please a professional readme is not a requirement yet in this project as it is a setup milestone
The app had been deployed to heroku  and live demo link was provided  maybe u did not read  with enough attention or did not run heroku open locally

**Review by uche-inyama — CHANGES_REQUESTED** [review]
## Changes Required

### Hi @che30 :slightly_smiling_face: 

I can see you have installed the required packages. 
However, some of the contents in the readme file are information from JavaScript project. Also, the live demo link should display a browser window without the calculator since this is milestone one.

#### That's it, revise the contents of your readme file, the submit another form for a code review.

### Happy Coding :slightly_smiling_face: 

#### ``` Uchechukwu Henry Inyama ```

**Review by uche-inyama — APPROVED** [review]
## Approved

### Hi che30 :slightly_smiling_face: 

Go on with the next milestone.

### Happy coding :man_technologist: 


#### ``` Uchechukwu Henry Inyama ```

**Pull request merged**
